title: MH-SOAR+ User Guide
description: Store Crew Documentation

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

navigation:
  items:
    - title: Introduction
      url: /
    - title: Getting Started
      url: /getting-started/
    - title: Creating an Order
      url: /creating-an-order/
    - title: Reviewing the Order
      url: /reviewing-the-order/
    - title: Payment
      url: /payment/
    - title: After Order
      url: /after-order/
    - title: Help
      url: /help/
